#@data/values
---
git_uri: git@github.com:blinkbitcoin/mavapay-client.git
git_branch: main
github_private_key: ((github-blinkbitcoin.private_key))
github_token: ((github.api_token))

gh_org: blinkbitcoin
gh_repository: mavapay-client