apiVersion: vendir.k14s.io/v1alpha1
kind: Config

# Relative to ci/
directories:
- path: ../.github/workflows/vendor
  contents:
  - path: . # Copy this folder out to ..
    git:
      url: https://github.com/blinkbitcoin/concourse-shared.git
      ref: 44a4608c9f8e288337d46c064776121a91c41450
    includePaths:
    - shared/actions/*
    excludePaths:
    - shared/actions/rust-*
    - shared/actions/docker-*
    - shared/actions/chart-*
    - shared/actions/tofu-*
    newRootPath: shared/actions

- path: ./vendor
  contents:
  - path: .
    git:
      url: https://github.com/blinkbitcoin/concourse-shared.git
      ref: 44a4608c9f8e288337d46c064776121a91c41450
    includePaths:
    - shared/ci/**/*
    excludePaths:
    - shared/ci/**/rust-*
    - shared/ci/**/chart-*
    - shared/ci/**/docker-*
    - shared/ci/**/tofu-*
    newRootPath: shared/ci

- path: ../bin/vendor
  contents:
  - path: .
    git:
      url: https://github.com/blinkbitcoin/concourse-shared
      ref: 44a4608c9f8e288337d46c064776121a91c41450
    includePaths:
    - shared/bin/**/*
    excludePaths:
    - shared/bin/**/rust-*
    - shared/bin/**/chart-*
    - shared/bin/**/docker-*
    - shared/bin/**/tofu-*
    newRootPath: shared/bin



