apiVersion: vendir.k14s.io/v1alpha1
kind: Config

directories:
- path: vendor
  contents:
  - path: .
    git:
      url: https://github.com/blinkbitcoin/concourse-shared.git
      ref: kn/mavapay_working
    includePaths:
    - shared/ci/**/*
    excludePaths:
    - shared/ci/**/rust-*
    - shared/ci/**/chart-*
    - shared/ci/**/docker-*
    newRootPath: shared/ci
