name: "Check code"
on:
  pull_request:
    branches: [main]
jobs:
  check-code:
    name: Check Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: pnpm install
      - name: Run check code
        run: pnpm code:check
